app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('create',views.create,name='create'),
    path('retrieve',views.retrieve,name='retrieve'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
]

proj56/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app1/',include('app1.urls',namespace='app1'))
]

app1/models.py
from django.db import models


# Create your models here.

class car(models.Model):
    c_name = models.CharField(max_length=30)
    color = models.CharField(max_length=30)
    price = models.IntegerField()

app1/forms.py
from django import forms
from app1.models import car
#create your forms here

class cars(forms.ModelForm):
    class Meta:
        model = car
        fields = '__all__'

app1/views.py
from django.shortcuts import render
from multiprocessing import context
from app1.models import car
from app1.forms import cars
from django.http import HttpResponseRedirect

# Create your views here.

def  index(request):
    context = {'msg':'this is index page'}
    return render(request,'app1/index.html',context)

def create(request):
    form = cars()
    if request.method == 'POST':
        form = cars(request.POST)
        if form.is_valid():
            form.save()
            form = cars()
        else:
            print('invalid formcourse')
    context = {'msg':'this is create page','form':form}
    return render (request,'app1/index.html',context)

def retrieve(request):
    Car = car.objects.all()
    context = {'msg':'This is the retrieve page','Car':Car}
    return render(request,'app1/index.html',context)

def update(request,id):
    if request.method == 'POST':
        Shabaz = car.objects.get(pk=id)
        form = cars(request.POST,instance=Shabaz)
        if form.is_valid():
            form.save()
            form = cars()
    else:
        Shabaz = car.objects.get(pk=id)
        form = cars(instance=Shabaz)
    a = {'msg':'This is update page','form':form}
    return render(request,'app1/update.html',a)

def delete(request,id):
    if request.method == 'POST':
        Shabaz = car.objects.get(pk=id)
        Shabaz.delete()
        return HttpResponseRedirect('/app1/retrieve')
        

templates/app1/index.html
{% extends 'base.html' %}
{% block b1 %}
    {{msg}}
    {% if form %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
    {% endif %}
    {% if Car %}
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>C_Name</th>
                    <th>Color</th>
                    <th>Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for i in Car  %}
                <tr>
                    <td>{{i.id}}</td>
                    <td>{{i.c_name}}</td>
                    <td>{{i.Color}}</td>
                    <td>{{i.price}}</td>
                    <td>
                        <a href="{% url 'app1:update' i.id %}">update</a>
                        <form action="{% url 'app1:delete' i.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="delete">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock b1 %}

templates/app1/update.html
{% extends 'base.html' %}
{% block b1 %}
{{msg}}
{% if form %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="add">
    </form>
{% endif %}
{% endblock b1 %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <link rel="stylesheet" href="{% static 'css/index2.css' %}">
</head>
<body>
    <div class="header">
        <h1>this is project page</h1>
        <button><a href="{% url 'index' %}">home</a></button>
        <button><a href="{% url 'app1:create' %}">create</a></button>
        <button><a href="{% url 'app1:retrieve' %}">Data</a></button>
    </div>
    <div class="c1">
        {% block b1 %}
        {% endblock b1 %}
    </div>
    <div class="footer">
        <h1>thanks</h1>
    </div>
</body>
</html>